name: decadal
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - xarray
  - netcdf4
  - dask
  - distributed
  - xskillscore
  - matplotlib
  - seaborn
  - cartopy
  - psutil
  - jupyterlab
